# Generated by Django 2.2 on 2021-04-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('total_shares', models.IntegerField()),
                ('rem_shares', models.IntegerField()),
                ('price', models.IntegerField()),
                ('created_on', models.CharField(max_length=15)),
                ('updated_at', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('item_id', models.IntegerField()),
                ('code', models.CharField(max_length=15)),
                ('companyName', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('type', models.CharField(default='Buy', max_length=4)),
                ('tif', models.CharField(max_length=5)),
                ('price', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.CharField(max_length=15)),
                ('updated_at', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='OrderBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('bp1', models.IntegerField()),
                ('bq1', models.IntegerField()),
                ('bp2', models.IntegerField()),
                ('bq2', models.IntegerField()),
                ('bp3', models.IntegerField()),
                ('bq3', models.IntegerField()),
                ('bp4', models.IntegerField()),
                ('bq4', models.IntegerField()),
                ('sq1', models.IntegerField()),
                ('sp1', models.IntegerField()),
                ('sq2', models.IntegerField()),
                ('sp2', models.IntegerField()),
                ('sq3', models.IntegerField()),
                ('sp3', models.IntegerField()),
                ('sq4', models.IntegerField()),
                ('sp4', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('seller_id', models.IntegerField()),
                ('buyer_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('quantity_fulfilled', models.IntegerField()),
                ('price', models.CharField(default=0, max_length=10)),
                ('offer_id', models.IntegerField()),
                ('created_on', models.CharField(max_length=15)),
                ('updated_at', models.CharField(max_length=15)),
            ],
        ),
    ]
