# Generated by Django 2.2 on 2021-04-13 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockex', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderBook',
        ),
    ]
