# Generated by Django 2.2 on 2021-04-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockex', '0003_auto_20210414_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='direction',
            field=models.CharField(default='buy', max_length=4),
        ),
    ]
