# Generated by Django 2.2 on 2021-04-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockex', '0004_auto_20210414_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='tif',
        ),
        migrations.AddField(
            model_name='offer',
            name='limit_price',
            field=models.CharField(default=0, max_length=15),
        ),
    ]
